/*
	Even Fibonacci numbers
	Problem 2

	Each new term in the Fibonacci sequence is generated by adding the previous two terms.
	By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million,
	find the sum of the even-valued terms.
	
	@Author Chris M. Perez
	@Date   3/26/2017
*/

package main
import "fmt"


func main(){
   sum := 0
   MAX := 4000000
   
   
   for i:=1;i<=MAX;i++ {
      if finonacci(i) >= MAX { break }
      if finonacci(i) % 2 == 0{
	 sum += finonacci(i)
      }
   }
   fmt.Println(sum)
}

func finonacci(value int) int {
   a , b , c := 1 , 1 , 0
  
   for i:=2;i<=value;i++ {
      a = b
      b = c
      c = a + b
   }
   return c
}
